### ISSUE TITLE
Depency Bot (Any)

### ISSUE THREAD

**Issue by fabianbernhart** [JadKHaddad/serial-vau#13]
- [x] manage `Rust` Dependencies
- [x] manage `NPM` Dependencies

**Comment by JadKHaddad** [comment]
How about renovate bot?

**Comment by fabianbernhart** [comment]
https://docs.renovatebot.com/getting-started/installing-onboarding/

**Comment by JadKHaddad** [comment]
So sieht es aus

**Comment by fabianbernhart** [comment]
> So sieht es aus

mach ma pls <3
